name: Deploy CRM Frontend to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'crm-frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Ajout de permissions explicites pour le job
    permissions:
      contents: write # Permet d'écrire sur le dépôt (nécessaire pour pousser sur gh-pages ou main)
      pages: write    # Permet de déployer sur GitHub Pages
      id-token: write # Nécessaire pour l'authentification OIDC de Pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend dependencies
        run: npm install
        working-directory: ./crm-frontend

      - name: Build Frontend
        run: npm run build
        working-directory: ./crm-frontend

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./crm-frontend/dist # Le dossier à déployer
          publish_branch: gh-pages # <-- C'est la branche où le site sera déployé (créée si elle n'existe pas)
          # cname: anaradaj.github.io # Laissez cette ligne commentée pour l'instant